server:
  port: 8486
  ssl:
    enabled: false
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      base-path: /api/actuator
openapi:
  theOpenShelf:
    base-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:8433/theopenshelf
    username: local
    password: local
  jpa:
    hibernate:
      ddl-auto: update # "update" pour dev, "validate" ou "none" pour prod
    show-sql: true # Affiche les requêtes SQL dans les logs
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: DEBUG
