server:
  port: 8486
  ssl:
    enabled: false
  servlet:
    context-path: /api
  session:
    cookie:
      secure: true
      same-site: none
      http-only: true

management:
  endpoints:
    web:
      base-path: /api/actuator
openapi:
  theOpenShelf:
    base-path: /api

oshelf:
  base-url: http://local.oshelf.org:4200
  frontend-url: http://local.oshelf.org:4200
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from:
    email: dev@mail.oshelf.org
    name: The Open Shelf dev environment
spring:
  datasource:
    url: jdbc:postgresql://localhost:8433/theopenshelf
    username: local
    password: local
  jpa:
    hibernate:
      ddl-auto: none # "update" pour dev, "validate" ou "none" pour prod
    show-sql: true # Affiche les requêtes SQL dans les logs
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # This shows the parameter values
