version: 2
updates:
  - package-ecosystem: "maven"
    directory: "platform-api"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "platform-ui"
    schedule:
      interval: "daily"
    groups:
      angular-packages:
        patterns:
          - "@angular/*"
          - "@taiga-ui/*"
          - "zone.js"
          - "rxjs"