package dev.theopenshelf.platform.entities;

public enum BorrowStatus {
    RESERVED_UNCONFIRMED,
    RESERVED_CONFIRMED,
    RESERVED_READY_TO_PICKUP,
    RESERVED_PICKUP_UNCONFIRMED,
    BORROWED_ACTIVE,
    BORROWED_DUE_TODAY,
    BORROWED_LATE,
    BORROWED_RETURN_UNCONFIRMED,
    RETURNED_EARLY,
    RETURNED_ON_TIME,
    RETURNED_LATE
}