package dev.theopenshelf.platform.entities;

public enum NotificationType {
    ITEM_AVAILABLE,
    ITEM_DUE,
    ITEM_BORROW_RESERVATION_DATE_START,
    ITEM_RESERVED_NO_LONGER_AVAILABLE,
    ITEM_NEW_RESERVATION_TO_CONFIRM,
    ITEM_NEW_PICKUP_TO_CONFIRM,
    ITEM_NEW_RETURN_TO_CONFIRM,
    ITEM_RESERVATION_APPROVED,
    ITEM_PICK_UP_APPROVED,
    ITEM_RETURN_APPROVED

}