name: release version

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # Specify the runner
    runs-on: ubuntu-latest

    # Skip workflow if the commit message contains "[ci skip]"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      # Step: Check out code
      - uses: actions/checkout@v1

      # Step: Prepare release version
      - name: Prepare release
        id: vars
        run: |
          sudo apt-get install -y libxml2-utils
          cd platform-api
          export VERSION=`xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml | sed -e  "s/-SNAPSHOT$//"`
          echo "app-version=$VERSION"
          echo "app-version=$VERSION" >> $GITHUB_ENV

      # Step: Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: /root/.m2
          key: ${{ runner.os }}-m2-${{ env.app-version }}
          restore-keys: ${{ runner.os }}-m2

      # Step: Build and Test
      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean verify -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"
      
      # Step: Verify Angular project compiles
      - name: Verify Angular project compiles
        run: |
          cd platform-ui
          npm ci # Install dependencies
          npm run build -- --configuration production # Build the project