name: test version

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Prepare test
        id: vars
        run: |
          sudo apt-get install libxml2-utils
          cp openapi.yaml platform-ui/
          cp openapi.yaml platform-api/
          cd platform-api
          export VERSION=`xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml | sed -e  "s/-SNAPSHOT$//"`
          echo "app-version=$VERSION"
          echo "app-version=$VERSION" >> $GITHUB_ENV

      - name: Deploy
        uses: qcastel/github-actions-update-helm@master
        with:
          branch-name: main

          git-release-bot-name: "bot-theopenshelf"
          git-release-bot-email: "bot@theopenshelf.dev"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          repository: git@github.com:theopenshelf/OpenShelf-saas.git
          file-path: dev/values.yaml

          yaml-paths: "openshelf-chart.backend.image.tag,openshelf-chart.frontend.image.tag"

          tag: 0.0.111

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}
